# Generated by Django 3.0.5 on 2021-06-06 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=20)),
                ('treeName', models.CharField(max_length=30)),
                ('treeAge', models.CharField(max_length=30)),
                ('treeImage', models.ImageField(upload_to='./media/photos/')),
                ('treeHealth', models.CharField(max_length=100)),
                ('treeGirth', models.CharField(max_length=10)),
                ('treeHeight', models.CharField(max_length=10)),
                ('treeLocation', models.CharField(max_length=100)),
                ('surveyDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=20)),
                ('treeName', models.CharField(max_length=30)),
                ('treeAge', models.CharField(max_length=30)),
                ('treeImage', models.CharField(max_length=2000)),
                ('treeHealth', models.CharField(max_length=100)),
                ('treeGirth', models.CharField(max_length=10)),
                ('treeHeight', models.CharField(max_length=10)),
                ('treeLocation', models.CharField(max_length=100)),
                ('surveyDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
